CC = g++
RMS= Assgn2-RMSCS19B1017.cpp
EDF= Assgn2-EDFCS19B1017.cpp
compile:
		${CC} ${RMS} -o rms.o;
		${CC} ${EDF} -o edf.o;
		./rms.o;
		./edf.o;
clean:
		rm *.o EDF-Log.txt EDF-Stats.txt RMS-Log.txt RMS-Stats.txt;
