Compile:
		g++ -pthread SrcAssgn3-tas-CS19B1017.cpp -o tas.out;
		g++ -pthread SrcAssgn3-cas-CS19B1017.cpp -o cas.out;
		g++ -pthread SrcAssgn3-cas-bounded-CS19B1017.cpp -o cas_b.out;
run:
		./tas.out;
		./cas.out;
		./cas_b.out;

clean:
		rm CAS-log.txt TAS-log.txt CAS_B-log.txt *.out;